[server]
enableCORS = false
enableXsrfProtection = true
enableStaticServing = true
headless = true
maxUploadSize = 5

[client]
showErrorDetails = false

[runner]
magicEnabled = false

[logger]
level = "error"
